import type { Alert, MarketQuote, NewsItem } from "../domain/types.js";
export class HomeAssistantClient {
  constructor(private readonly token:string,private readonly fetcher:typeof fetch=fetch,private readonly baseUrl="http://supervisor/core/api",private readonly timeoutMs=15_000){}
  async setState(entityId:string,state:string,attributes:Readonly<Record<string,unknown>>={}):Promise<void>{await this.request(`/states/${entityId}`,{method:"POST",body:JSON.stringify({state,attributes})});}
  async notify(service:string,alert:Alert):Promise<void>{await this.request(`/services/notify/${encodeURIComponent(service)}`,{method:"POST",body:JSON.stringify({title:alert.title,message:alert.message,data:alert.url?{url:alert.url}: {}})});}
  async publishOverview(news:readonly NewsItem[],quotes:readonly MarketQuote[]):Promise<void>{const fc=news.filter(n=>n.topic==="fc_porto"),ai=news.filter(n=>n.topic==="ai"),fabrizio=news.filter(n=>n.source==="Fabrizio Romano");await Promise.all([this.setState("sensor.intelligence_fc_porto_news",String(fc.length),this.newsAttributes(fc[0])),this.setState("sensor.intelligence_ai_news",String(ai.length),this.newsAttributes(ai[0])),this.setState("sensor.intelligence_fabrizio_romano_news",String(fabrizio.length),this.newsAttributes(fabrizio[0])),...quotes.map(q=>this.setState(`sensor.intelligence_${q.symbol.toLowerCase()}_price`,String(q.price),{change_percent:q.changePercent,currency:q.currency,observed_at:q.observedAt}))]);}
  private newsAttributes(item:NewsItem|undefined):Readonly<Record<string,unknown>>{return{latest:item?.title??"",latest_url:item?.url??"",latest_source:item?.source??"",latest_published_at:item?.publishedAt??""};}
  private async request(path:string,init:RequestInit):Promise<void>{const r=await this.fetcher(`${this.baseUrl}${path}`,{...init,headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json"},signal:AbortSignal.timeout(this.timeoutMs)});if(!r.ok)throw new Error(`Home Assistant API ${path} returned ${r.status}`);}
}
