import type { Alert, HubHealth, MarketQuote, NewsItem } from "../domain/types.js";
export class HomeAssistantClient {
  constructor(private readonly token:string,private readonly fetcher:typeof fetch=fetch,private readonly baseUrl="http://supervisor/core/api",private readonly timeoutMs=15_000){}
  async setState(entityId:string,state:string,attributes:Readonly<Record<string,unknown>>={}):Promise<void>{await this.request(`/states/${entityId}`,{method:"POST",body:JSON.stringify({state,attributes})});}
  async notify(service:string,alert:Alert):Promise<void>{await this.request(`/services/notify/${encodeURIComponent(service)}`,{method:"POST",body:JSON.stringify({title:alert.title,message:alert.message,data:alert.url?{url:alert.url}: {}})});}
  async publishOverview(news:readonly NewsItem[],quotes:readonly MarketQuote[],marketAlertPercent=3):Promise<void>{const fc=news.filter(n=>n.topic==="fc_porto"),ai=news.filter(n=>n.topic==="ai"),fabrizio=news.filter(n=>n.source==="Fabrizio Romano");await Promise.all([this.setState("sensor.intelligence_fc_porto_news",String(fc.length),this.newsAttributes(fc)),this.setState("sensor.intelligence_ai_news",String(ai.length),this.newsAttributes(ai)),this.setState("sensor.intelligence_fabrizio_romano_news",String(fabrizio.length),this.newsAttributes(fabrizio)),this.setState("sensor.intelligence_market_overview",String(quotes.length),{alert_threshold:marketAlertPercent,quotes:quotes.slice(0,12).map(q=>({symbol:q.symbol,price:q.price,change_percent:q.changePercent,currency:q.currency,observed_at:q.observedAt,alerting:Math.abs(q.changePercent)>=marketAlertPercent}))}),...quotes.map(q=>this.setState(`sensor.intelligence_${q.symbol.toLowerCase()}_price`,String(q.price),{change_percent:q.changePercent,currency:q.currency,observed_at:q.observedAt}))]);}
  private newsAttributes(items:readonly NewsItem[]):Readonly<Record<string,unknown>>{const latest=items[0];return{latest:this.truncate(latest?.title??"",300),latest_url:this.truncate(latest?.url??"",1_000),latest_source:this.truncate(latest?.source??"",120),latest_published_at:this.truncate(latest?.publishedAt??"",40),items:items.slice(0,5).map(item=>({title:this.truncate(item.title,300),url:this.truncate(item.url,1_000),source:this.truncate(item.source,120),published_at:this.truncate(item.publishedAt,40),category:item.category,relevance:item.relevanceScore}))};}
  async publishHealth(health:HubHealth):Promise<void>{const news=health.collectors.news,markets=health.collectors.markets;await this.setState("sensor.intelligence_hub_status",health.status,{news_status:news.status,news_errors:news.errors.slice(0,5).map(error=>this.truncate(error,500)),news_last_attempt_at:news.lastAttemptAt??"",news_last_success_at:news.lastSuccessAt??"",markets_status:markets.status,markets_errors:markets.errors.slice(0,5).map(error=>this.truncate(error,500)),markets_last_attempt_at:markets.lastAttemptAt??"",markets_last_success_at:markets.lastSuccessAt??""});}
  private truncate(value:string,maxLength:number):string{return value.slice(0,maxLength);}
  private async request(path:string,init:RequestInit):Promise<void>{const r=await this.fetcher(`${this.baseUrl}${path}`,{...init,headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json"},signal:AbortSignal.timeout(this.timeoutMs)});if(!r.ok)throw new Error(`Home Assistant API ${path} returned ${r.status}`);}
}
